<?php
session_start();
require_once '../../models/Sales.php';

// Check manager authentication
if (!isset($_SESSION['manager_logged_in']) || $_SESSION['manager_logged_in'] !== true || $_SESSION['role'] !== 'Manager') {
    header('HTTP/1.1 403 Forbidden');
    exit('Unauthorized access');
}

$salesClass = new Sales();

// Get date parameters with validation
$startDate = isset($_GET['start']) && !empty($_GET['start']) ? $_GET['start'] : date('Y-m-d', strtotime('-30 days'));
$endDate = isset($_GET['end']) && !empty($_GET['end']) ? $_GET['end'] : date('Y-m-d');

// Validate dates
if (strtotime($startDate) > strtotime($endDate)) {
    header('HTTP/1.1 400 Bad Request');
    exit('Invalid date range');
}

try {
    // Get sales data for the date range
    $salesData = $salesClass->getSalesReport($startDate, $endDate);

    // Set headers for CSV download
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="sales_report_' . date('Y-m-d') . '.csv"');

    // Create output stream
    $output = fopen('php://output', 'w');

    // Add UTF-8 BOM for Excel compatibility
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

    // Write CSV header
    fputcsv($output, [
        'Date',
        'Order ID',
        'Product',
        'Category',
        'Quantity',
        'Unit Price',
        'Total Amount',
        'Payment Method',
        'Status'
    ]);

    // Write data rows
    foreach ($salesData as $row) {
        fputcsv($output, [
            $row['order_date'],
            $row['order_id'],
            $row['product_name'],
            $row['category'],
            $row['quantity'],
            number_format($row['unit_price'], 2),
            number_format($row['total_amount'], 2),
            $row['payment_method'],
            $row['order_status']
        ]);
    }

    // Add summary section
    fputcsv($output, []); // Empty line
    fputcsv($output, ['Summary']);
    fputcsv($output, ['Report Period:', "From $startDate to $endDate"]);
    fputcsv($output, ['Total Orders:', count(array_unique(array_column($salesData, 'order_id')))]);
    fputcsv($output, ['Total Sales:', '₱' . number_format(array_sum(array_column($salesData, 'total_amount')), 2)]);
    fputcsv($output, ['Generated On:', date('Y-m-d H:i:s')]);
    fputcsv($output, ['Generated By:', $_SESSION['username']]);

    fclose($output);
    exit();

} catch (Exception $e) {
    error_log("Error generating sales report: " . $e->getMessage());
    header('HTTP/1.1 500 Internal Server Error');
    exit('Error generating report');
}
