<?php
session_start();
require_once '../../models/Order.php';

// Check manager authentication
if (!isset($_SESSION['manager_logged_in']) || $_SESSION['manager_logged_in'] !== true || $_SESSION['role'] !== 'Manager') {
    header('HTTP/1.1 403 Forbidden');
    exit('Unauthorized access');
}

$orderClass = new Order();

// Get date parameters
$startDate = isset($_GET['start']) ? $_GET['start'] : date('Y-m-d', strtotime('-30 days'));
$endDate = isset($_GET['end']) ? $_GET['end'] : date('Y-m-d');

// Set headers for CSV download
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="orders_' . date('Y-m-d') . '.csv"');

// Create output stream
$output = fopen('php://output', 'w');

// Add UTF-8 BOM for Excel compatibility
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Write CSV header
fputcsv($output, [
    'Order ID',
    'Date',
    'Customer',
    'Items',
    'Total Amount',
    'Status'
]);

// Get orders for the date range and write to CSV
$orders = $orderClass->getOrdersByDateRange($startDate, $endDate);
foreach ($orders as $order) {
    fputcsv($output, [
        '#' . $order['order_id'],
        $order['order_date'],
        $order['customer_name'],
        $order['item_count'],
        number_format($order['total_amount'], 2),
        $order['status']
    ]);
}

// Add summary section
fputcsv($output, []); // Empty line
fputcsv($output, ['Report Summary']);
fputcsv($output, ['Period:', "From $startDate to $endDate"]);
fputcsv($output, ['Total Orders:', count($orders)]);
fputcsv($output, ['Generated On:', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated By:', $_SESSION['username']]);

fclose($output);
