import { StyleSheet, Platform } from "react-native";
import { COLORS } from "@/constants/Colors";

export const marketStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f8f8",
    // This was causing the white space issue - remove platform-specific code
    paddingTop: 0,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: COLORS.primary,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.light,
    letterSpacing: 0.5,
  },
  cartButton: {
    position: "relative",
  },
  cartBadge: {
    position: "absolute",
    top: -5,
    right: -10,
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cartBadgeText: {
    color: COLORS.light,
    fontSize: 12,
    fontWeight: "bold",
  },
  searchContainer: {
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 6,
    marginBottom: 5,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.light,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    color: COLORS.dark,
    fontSize: 15,
  },
  categoryFilterContainer: {
    backgroundColor: "#f8f8f8",
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  categoriesContainer: {
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  categoryButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 8,
    marginVertical: 4,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    backgroundColor: "#f0f0f0",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  categoryButtonActive: {
    backgroundColor: COLORS.accent,
  },
  categoryText: {
    fontSize: 14,
    color: COLORS.dark,
    fontWeight: "500",
    textAlignVertical: "center",
  },
  categoryTextActive: {
    color: COLORS.light,
    fontWeight: "bold",
  },
  listContainer: {
    padding: 10,
    paddingBottom: 20,
  },
  footerLoader: {
    paddingVertical: 20,
    alignItems: "center",
  },
  noProductsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 50,
    paddingHorizontal: 20,
  },
  noProductsText: {
    fontSize: 18,
    marginTop: 16,
    marginBottom: 8,
    color: COLORS.muted,
    fontWeight: "500",
    textAlign: "center",
  },
  refreshButton: {
    marginTop: 15,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: COLORS.accent,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  refreshButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
  },
  pickupButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  // New orders button style
  ordersButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 10,
  },
  ordersButtonText: {
    color: COLORS.light,
    fontSize: 13,
    fontWeight: "bold",
    marginLeft: 4,
  },
});

export const productStyles = StyleSheet.create({
  productCard: {
    flex: 1,
    margin: 8,
    borderRadius: 16,
    backgroundColor: "white",
    overflow: "hidden",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    maxWidth: "47%",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
  },
  productImageContainer: {
    height: 130,
    width: "100%",
    backgroundColor: "#f0f0f0",
    position: "relative",
  },
  productImage: {
    height: "100%",
    width: "100%",
  },
  placeholderImage: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
  },
  categoryBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  categoryBadgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  productDetails: {
    padding: 12,
  },
  productName: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
    color: COLORS.dark,
  },
  productFarm: {
    fontSize: 13,
    color: "#777",
    marginBottom: 8,
  },
  productPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  productPrice: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.accent,
  },
  stockBadge: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    backgroundColor: "#e8f5e9",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#c8e6c9",
  },
  stockBadgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#2e7d32",
  },
  outOfStockBadge: {
    backgroundColor: "#ffebee",
    borderColor: "#ffcdd2",
  },
  outOfStockText: {
    color: "#c62828",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.accent,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 5,
    gap: 3,
  },
  addButtonText: {
    color: COLORS.light,
    fontSize: 12,
    fontWeight: "bold",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 15,
    color: COLORS.dark,
  },
  closeButton: {
    padding: 5,
  },
  modalContent: {
    flex: 1,
    padding: 15,
  },
  modalTabs: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  modalTab: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.accent,
  },
  tabIcon: {
    marginRight: 8,
  },
  tabText: {
    color: COLORS.dark,
    fontWeight: "500",
  },
  activeTabText: {
    color: COLORS.accent,
    fontWeight: "bold",
  },
  productImageContainerLarge: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 20,
    backgroundColor: COLORS.light,
  },
  productImageLarge: {
    width: "100%",
    height: "100%",
  },
  placeholderImageLarge: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.primary + "50",
  },
  detailRow: {
    flexDirection: "row",
    marginBottom: 10,
  },
  detailLabel: {
    fontWeight: "bold",
    width: 80,
    color: COLORS.dark,
  },
  detailValue: {
    flex: 1,
    color: COLORS.dark,
  },
  descriptionContainer: {
    marginTop: 10,
  },
  descriptionLabel: {
    fontWeight: "bold",
    marginBottom: 5,
    color: COLORS.dark,
  },
  descriptionText: {
    lineHeight: 20,
    color: COLORS.dark,
  },
  addToCartButton: {
    backgroundColor: COLORS.accent,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    borderRadius: 8,
    marginTop: 20,
  },
  addToCartButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
  },
  feedbackContainer: {
    flex: 1,
  },
  loginPrompt: {
    textAlign: "center",
    marginVertical: 20,
    color: COLORS.muted,
    fontStyle: "italic",
  },
  feedbackListContainer: {
    marginTop: 20,
    flex: 1,
  },
  feedbackHeader: {
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  feedbackHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  feedbackHeaderSubtitle: {
    fontSize: 14,
    color: COLORS.muted,
  },
  feedbackFooterNote: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
    padding: 12,
    borderRadius: 6,
    marginTop: 16,
  },
  feedbackFooterText: {
    fontSize: 13,
    color: COLORS.muted,
    marginLeft: 6,
    flex: 1,
    flexWrap: "wrap",
  },
});

export const cartStyles = StyleSheet.create({
  cartContainer: {
    flex: 1,
    backgroundColor: "#f8f8f8",
  },
  cartHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: COLORS.primary,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  cartTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.light,
    letterSpacing: 0.5,
  },
  cartCloseButton: {
    padding: 5,
  },
  emptyCartContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 50,
    paddingHorizontal: 20,
  },
  emptyCartText: {
    fontSize: 18,
    marginTop: 16,
    marginBottom: 8,
    color: COLORS.muted,
    fontWeight: "500",
    textAlign: "center",
  },
  continueShoppingButton: {
    marginTop: 15,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: COLORS.accent,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  continueShoppingText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
  },
  cartList: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  cartItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    marginVertical: 5,
    backgroundColor: "#fff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cartItemImageContainer: {
    width: 60,
    height: 60,
    borderRadius: 8,
    overflow: "hidden",
    marginRight: 10,
    backgroundColor: "#f0f0f0",
  },
  cartItemImage: {
    width: "100%",
    height: "100%",
  },
  cartItemPlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0f0f0",
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemName: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  cartItemPrice: {
    fontSize: 14,
    color: COLORS.muted,
    marginVertical: 2,
  },
  cartItemFarm: {
    fontSize: 13,
    color: "#777",
  },
  cartItemActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  quantityButton: {
    padding: 5,
    backgroundColor: "#f0f0f0",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  quantityText: {
    marginHorizontal: 10,
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  cartItemTotal: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.accent,
    marginRight: 10,
  },
  removeButton: {
    padding: 5,
  },
  cartSummary: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    backgroundColor: "#fff",
  },
  cartTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  cartTotalLabel: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  cartTotalAmount: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.accent,
  },
  checkoutButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  checkoutButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
    marginRight: 10,
  },
});

export const paymentStyles = StyleSheet.create({
  paymentContainer: {
    flex: 1,
    backgroundColor: "#f8f8f8",
  },
  paymentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: COLORS.primary,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  paymentTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.light,
    letterSpacing: 0.5,
  },
  paymentCloseButton: {
    padding: 5,
  },
  paymentContent: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  orderSummarySection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.dark,
    marginBottom: 10,
  },
  orderInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  orderInfoLabel: {
    fontSize: 16,
    color: COLORS.dark,
  },
  orderInfoValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.accent,
  },
  paymentMethodSection: {
    marginBottom: 20,
  },
  paymentMethodOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paymentMethodOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 5,
    marginHorizontal: 5,
    backgroundColor: "#f0f0f0",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  paymentMethodSelected: {
    backgroundColor: COLORS.accent,
  },
  paymentMethodText: {
    fontSize: 14,
    color: COLORS.dark,
    fontWeight: "500",
    textAlignVertical: "center",
    marginTop: 5,
  },
  paymentMethodTextSelected: {
    color: COLORS.light,
  },
  checkIcon: {
    position: "absolute",
    top: 5,
    right: 5,
  },
  cardDetailsSection: {
    marginBottom: 20,
  },
  inputContainer: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 14,
    color: COLORS.dark,
    marginBottom: 5,
  },
  input: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    fontSize: 16,
    color: COLORS.dark,
  },
  inputRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bankDetailsSection: {
    marginBottom: 20,
  },
  bankInstructions: {
    fontSize: 14,
    color: COLORS.dark,
    marginBottom: 10,
  },
  bankInfo: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    marginBottom: 10,
  },
  bankInfoItem: {
    fontSize: 14,
    color: COLORS.dark,
    marginBottom: 5,
  },
  bankNote: {
    fontSize: 14,
    color: COLORS.muted,
  },
  cashPickupSection: {
    marginBottom: 20,
  },
  cashPickupInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  cashPickupText: {
    fontSize: 14,
    color: COLORS.dark,
    marginLeft: 10,
  },
  cashPickupNote: {
    fontSize: 14,
    color: COLORS.muted,
  },
  errorContainer: {
    backgroundColor: "#ffebee",
    borderRadius: 8,
    padding: 12,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#ffcdd2",
  },
  errorText: {
    color: "#c62828",
    fontSize: 14,
  },
  paymentActions: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    backgroundColor: "#fff",
  },
  paymentButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  paymentButtonDisabled: {
    backgroundColor: COLORS.muted,
  },
  paymentButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
    marginRight: 10,
  },
});

export const pickupStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f8f8",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: COLORS.primary,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerIcon: {
    marginRight: 10,
  },
  headerButtons: {
    flexDirection: "row",
    alignItems: "center",
  },
  helpButton: {
    marginRight: 15,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.light,
  },
  closeButton: {
    padding: 5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: COLORS.muted,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.primary,
    marginTop: 20,
  },
  emptyText: {
    fontSize: 18,
    textAlign: "center",
    marginTop: 20,
    marginBottom: 20,
    color: COLORS.muted,
  },
  emptyActionButtons: {
    flexDirection: "row",
    marginTop: 20,
  },
  refreshButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    flexDirection: "row",
    alignItems: "center",
  },
  refreshButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
  },
  shopButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
  },
  shopButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 16,
  },
  listContainer: {
    padding: 10,
    paddingBottom: 20,
  },
  pickupItem: {
    backgroundColor: COLORS.light,
    borderRadius: 10,
    marginBottom: 15,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  statusStrip: {
    height: 4,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginBottom: 10,
  },
  pickupHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  pickupInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  pickupId: {
    fontSize: 16,
    fontWeight: "bold",
    marginRight: 10,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#c8e6c9",
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#2e7d32",
  },
  actionButton: {
    backgroundColor: COLORS.accent,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 5,
  },
  actionButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
    fontSize: 12,
    marginLeft: 5,
  },
  pickupDetails: {
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    padding: 12,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  detailText: {
    fontSize: 14,
    marginLeft: 8,
    flex: 1,
  },
  orderSummary: {
    marginTop: 10,
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    padding: 10,
  },
  orderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  orderTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  orderSummaryLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  orderSummaryText: {
    fontSize: 14,
    color: COLORS.dark,
  },
  orderTotal: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  orderItemsList: {
    marginTop: 10,
    backgroundColor: "#f2f8ff",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#d0e1f9",
  },
  orderItemsHeader: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    color: COLORS.primary,
  },
  orderTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#d0e1f9",
  },
  orderTotalLabel: {
    fontSize: 16,
    fontWeight: "bold",
  },
  orderGrandTotal: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  orderItemContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    backgroundColor: "#fff",
    marginVertical: 2,
    borderRadius: 4,
  },
  orderItemInfo: {
    flex: 1,
  },
  orderItemName: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  orderItemDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 3,
  },
  orderItemQuantity: {
    fontSize: 13,
    color: COLORS.primary,
    fontWeight: "500",
  },
  orderItemPrice: {
    fontSize: 13,
    color: COLORS.muted,
  },
  orderItemSubtotal: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.accent,
    marginLeft: 10,
  },
  expandHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  expandHintText: {
    fontSize: 14,
    color: COLORS.muted,
    marginRight: 5,
  },
  itemCount: {
    fontWeight: "bold",
    color: COLORS.primary,
  },
  totalAmount: {
    fontWeight: "bold",
    color: COLORS.accent,
  },

  // Reschedule modal styles
  rescheduleModalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  rescheduleModal: {
    width: "90%",
    backgroundColor: COLORS.light,
    borderRadius: 10,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  rescheduleTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
  },
  modalDivider: {
    height: 1,
    backgroundColor: COLORS.muted,
    marginVertical: 10,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.dark,
    marginBottom: 5,
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    padding: 12,
    borderRadius: 5,
    marginBottom: 15,
  },
  dateButtonText: {
    marginLeft: 10,
    fontSize: 16,
  },
  notesInput: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 5,
    padding: 10,
    marginBottom: 20,
    color: COLORS.dark,
    height: 100,
    textAlignVertical: "top",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#f0f0f0",
    marginRight: 10,
  },
  cancelButtonText: {
    color: COLORS.dark,
    fontWeight: "bold",
  },
  saveButton: {
    backgroundColor: COLORS.primary,
  },
  saveButtonText: {
    color: COLORS.light,
    fontWeight: "bold",
  },
  modalFooter: {
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.muted,
  },
  modalFooterText: {
    fontSize: 12,
    color: COLORS.muted,
    textAlign: "center",
  },

  // Custom date picker styles
  customDatePicker: {
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
  },
  datePickerSection: {
    marginBottom: 10,
  },
  datePickerLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.dark,
    marginBottom: 5,
  },
  datePickerControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  datePickerControlButton: {
    backgroundColor: COLORS.primary,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  datePickerButtonText: {
    color: COLORS.light,
    fontSize: 18,
    fontWeight: "bold",
  },
  datePickerValue: {
    fontSize: 16,
    color: COLORS.dark,
    fontWeight: "600",
    paddingHorizontal: 10,
  },

  // Calendar picker styles
  calendarPickerContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
  },
  timeSelectionContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 15,
    paddingHorizontal: 10,
  },
  timeLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  timeButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  timeButtonText: {
    fontSize: 16,
    color: COLORS.dark,
    marginLeft: 10,
  },

  // Pickup status styles
  statusIndicator: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  statusBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 10,
  },
  statusRowText: {
    color: COLORS.light,
    fontSize: 12,
    fontWeight: "600",
  },
  statusIcon: {
    marginRight: 4,
  },
  // Add this section for the status progress indicator
  statusProgressContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 5,
    paddingHorizontal: 5,
  },
  statusProgressStep: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.muted,
  },
  statusProgressStepActive: {
    backgroundColor: COLORS.primary,
  },
  statusProgressLine: {
    flex: 1,
    height: 2,
    backgroundColor: COLORS.muted,
    marginHorizontal: 5,
  },
  statusProgressLineActive: {
    backgroundColor: COLORS.primary,
  },
  statusLabelsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  statusLabel: {
    fontSize: 10,
    color: COLORS.muted,
    textAlign: "center",
    width: 60,
  },
  statusLabelActive: {
    color: COLORS.primary,
    fontWeight: "bold",
  },

  // Order feedback styles
  orderInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  orderReference: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
    marginLeft: 8,
  },
  orderDate: {
    fontSize: 14,
    color: COLORS.muted,
    marginLeft: 8,
  },
  productList: {
    padding: 16,
    backgroundColor: COLORS.light + "F5",
    borderTopWidth: 1,
    borderTopColor: "#eeeeee",
  },
  productsTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.dark,
    marginBottom: 16,
  },
  productItem: {
    marginBottom: 8,
  },
  // Tab interface styles
  tabContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.light,
    borderRadius: 8,
    marginHorizontal: 16,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    overflow: "hidden",
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    backgroundColor: "transparent",
  },
  activeTab: {
    backgroundColor: "#f0f8ff",
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.muted,
    marginLeft: 6,
  },
  activeTabText: {
    color: COLORS.primary,
    fontWeight: "bold",
  },
  errorText: {
    marginTop: 12,
    marginBottom: 16,
    fontSize: 16,
    color: COLORS.accent,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    marginLeft: 8,
    color: COLORS.light,
    fontWeight: "bold",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 8,
    marginHorizontal: 16,
    marginTop: 16,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.muted,
    marginBottom: 16,
    marginHorizontal: 16,
  },

  // Error container style
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
});
